<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{RouterView,useRoute,useRouter}from'vue-router';import{api,applyMemberSession,applySession,session}from'./api'
const login=reactive({username:'admin',password:''}),error=ref(''),loading=ref(true);const route=useRoute(),router=useRouter()
const enterpriseNav=[['dashboard','实时大盘','⌂'],['devices','设备管理','▣'],['accounts','直播间与账号','◈'],['reports','检测报告','◎'],['alerts','告警中心','!'],['workorders','故障工单','✓'],['members','成员权限','♙'],['subscription','订阅与告警','◇']]
const platformNav=[['platform','企业客户','◆'],['realtime','实时设备','◉']]
const memberNav=[['realtime','实时设备','◉']];const nav=computed(()=>session.enterpriseToken?memberNav:session.role==='platform_super'?platformNav:enterpriseNav);const page=computed(()=>String(route.name||''));const title=computed(()=>nav.value.find(x=>x[0]===page.value)?.[1]||'管理中心')
async function boot(){try{const x=await api('/tk-api/session');applySession(x);await router.replace({name:session.role==='platform_super'?'platform':'dashboard'})}catch{const token=sessionStorage.getItem('vd-member-token'),raw=sessionStorage.getItem('vd-member');if(token&&raw){const member=JSON.parse(raw);applyMemberSession({token,member,permissions:member.permissions});try{await api('/api/v2/organization/options');await router.replace({name:'realtime'})}catch{sessionStorage.clear();session.loggedIn=false}}}finally{loading.value=false}}
async function doLogin(){error.value='';try{const x=await api('/tk-api/login',{method:'POST',body:JSON.stringify(login)});applySession(x);await router.replace({name:session.role==='platform_super'?'platform':'dashboard'})}catch{try{const x=await api('/api/v2/auth/login',{method:'POST',body:JSON.stringify(login)});applyMemberSession(x);await router.replace({name:'realtime'})}catch(e:any){error.value=e.message}}}
async function logout(){if(session.enterpriseToken){sessionStorage.clear();location.reload();return}await api('/tk-api/logout',{method:'POST'});location.reload()}
function go(name:string){router.push({name})}
onMounted(boot)
</script>
<template><div v-if="loading" class="boot-screen"><div class="brand-mark">VD</div><p>正在建立安全连接…</p></div><div v-else-if="!session.loggedIn" class="login-shell"><section class="login-story"><div class="story-top"><div class="brand-mark">VD</div><span>VD NEXUS · ENTERPRISE</span></div><div><span class="eyebrow light">LIVE OPERATIONS INTELLIGENCE</span><h1>让每一场直播<br><em>始终准备就绪</em></h1><p>集中掌握企业名下电脑的环境、准备度与软件运行状态。</p></div><footer>不采集屏幕、账号密码、Cookie及浏览器会话</footer></section><section class="login-panel"><div class="login-card"><span class="eyebrow">SECURE MANAGEMENT ACCESS</span><h2>登录管理控制台</h2><p>平台超级管理员与企业成员使用同一入口</p><label>登录账号<input v-model="login.username" autocomplete="username"></label><label>登录密码<input v-model="login.password" type="password" @keyup.enter="doLogin"></label><div v-if="error" class="form-error">{{error}}</div><button class="primary login-button" @click="doLogin">安全登录 <span>→</span></button></div></section></div><div v-else class="app-shell"><aside><div class="brand"><div class="brand-mark small">VD</div><div><b>VD NEXUS</b><span>{{session.role==='platform_super'?'平台运营控制中心':'企业开播管理平台'}}</span></div></div><div class="tenant-chip" v-if="session.role!=='platform_super'"><i></i><div><span>当前企业</span><b>Organization #{{session.tenantId}}</b></div></div><nav><span class="nav-label">运营监控</span><button v-for="item in nav" :class="{active:page===item[0]}" @click="go(item[0])"><i>{{item[2]}}</i><span>{{item[1]}}</span><b>›</b></button></nav><div class="aside-foot"><span class="avatar">{{session.username.slice(0,1).toUpperCase()}}</span><div><b>{{session.username}}</b><small>{{session.role}}</small></div><button @click="logout">↪</button></div></aside><main><header class="topbar"><div><span class="eyebrow">WEIDU LIVE OPERATIONS</span><h1>{{title}}</h1></div><div class="top-actions"><span class="system-online"><i></i>服务运行正常</span><div class="user-mini"><span class="avatar">{{session.username.slice(0,1).toUpperCase()}}</span><div><b>{{session.username}}</b><small>{{session.role}}</small></div></div></div></header><div class="content"><RouterView/></div><nav class="mobile-nav"><button v-for="item in nav.slice(0,4)" :class="{active:page===item[0]}" @click="go(item[0])"><i>{{item[2]}}</i><span>{{item[1]}}</span></button></nav></main></div></template>
