<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{RouterView,useRoute,useRouter}from'vue-router';import{api,applyMemberSession,applySession,clearMemberSession,featureEnabled,hasPermission,loadBootstrap,session}from'./api'
const login=reactive({organization_code:'',username:'admin',password:''}),error=ref(''),loading=ref(true);const route=useRoute(),router=useRouter()
const platformNav=[
 {name:'platform-overview',label:'平台总览',icon:'⌂'},{name:'platform-organizations',label:'企业管理',icon:'◆'},{name:'platform-subscriptions',label:'订阅与套餐',icon:'◇'},{name:'platform-features',label:'功能模块',icon:'▦'},{name:'platform-organization-features',label:'企业功能授权',icon:'◎'},{name:'platform-devices',label:'设备功能灰度',icon:'▣'},{name:'platform-roles',label:'角色权限矩阵',icon:'☷'},{name:'platform-providers',label:'Provider',icon:'↗'},{name:'platform-releases',label:'版本发布',icon:'↑'},{name:'platform-settings',label:'系统配置',icon:'⚙'},{name:'platform-alerts',label:'平台告警',icon:'!'},{name:'platform-audit',label:'平台审计',icon:'≡'}]
const enterpriseNav=[
 {name:'enterprise-dashboard',label:'工作台',icon:'⌂'},{name:'enterprise-live',label:'直播中心',icon:'◉',feature:'live_dashboard',permission:'organization.read'},{name:'enterprise-devices',label:'设备中心',icon:'▣',feature:'device_center',permission:'devices.read'},{name:'enterprise-analytics',label:'运营分析',icon:'◎',feature:'report_center',permission:'organization.read'},{name:'enterprise-alerts',label:'告警中心',icon:'!',feature:'alert_center',permission:'organization.read'},{name:'enterprise-organization',label:'组织管理',icon:'♙',feature:'member_management',permission:'members.manage'},{name:'enterprise-settings',label:'系统设置',icon:'⚙',permission:'organization.read'}]
const nav=computed(()=>session.role==='platform_super'?platformNav:enterpriseNav.filter(x=>!session.enterpriseToken||featureEnabled(x.feature)&&hasPermission(x.permission)));const page=computed(()=>String(route.name||''));const title=computed(()=>String(route.meta.title||nav.value.find(x=>x.name===page.value)?.label||'管理中心'))
async function memberReady(){await loadBootstrap();const onboarding=session.bootstrap?.organization?.onboarding;if(onboarding&&!onboarding.completed){if(route.name!=='enterprise-onboarding')await router.replace({name:'enterprise-onboarding'});return}if(route.meta.audience!=='enterprise'||route.name==='enterprise-onboarding')await router.replace({name:'enterprise-dashboard'})}
async function boot(){try{const x=await api('/tk-api/session');applySession(x);if(route.meta.audience!=='platform')await router.replace({name:'platform-overview'})}catch{const token=sessionStorage.getItem('vd-member-token'),raw=sessionStorage.getItem('vd-member');if(token&&raw){const member=JSON.parse(raw);applyMemberSession({token,member,organization_code:member.organization_code,permissions:member.permissions});try{await memberReady()}catch{clearMemberSession()}}}finally{loading.value=false}}
async function doLogin(){error.value='';try{const x=await api('/tk-api/login',{method:'POST',body:JSON.stringify({username:login.username,password:login.password})});applySession(x);await router.replace({name:session.role==='platform_super'?'platform-overview':'enterprise-dashboard'})}catch{try{const x=await api('/api/v2/auth/login',{method:'POST',body:JSON.stringify(login)});applyMemberSession({...x,organization_code:login.organization_code});await memberReady()}catch(e:any){error.value=e.code==='AUTH_ORGANIZATION_REQUIRED'?'请输入企业代码后重新登录':e.message}}}
async function logout(){if(session.enterpriseToken){clearMemberSession();await router.replace({name:'enterprise-dashboard'});return}await api('/tk-api/logout',{method:'POST'});location.reload()}
function go(name:string){router.push({name})}
onMounted(boot)
</script>
<template><div v-if="loading" class="boot-screen"><div class="brand-mark">VD</div><p>正在建立安全连接……</p></div><div v-else-if="!session.loggedIn" class="login-shell"><section class="login-story"><div class="story-top"><div class="brand-mark">VD</div><span>VD NEXUS · ENTERPRISE</span></div><div><span class="eyebrow light">LIVE OPERATIONS MANAGEMENT</span><h1>让每一场直播<br><em>始终准备就绪</em></h1><p>集中掌握企业设备、直播间、环境状态和异常处理进度。</p></div><footer>不采集屏幕、账号密码、Cookie 及浏览器会话</footer></section><section class="login-panel"><div class="login-card"><span class="eyebrow">SECURE MANAGEMENT ACCESS</span><h2>登录管理控制台</h2><p>平台管理员可直接登录；企业成员请同时填写企业代码。</p><label>企业代码（企业成员）<input v-model="login.organization_code" autocomplete="organization" placeholder="例如 ACME-US"></label><label>登录账号<input v-model="login.username" autocomplete="username"></label><label>登录密码<input v-model="login.password" type="password" autocomplete="current-password" @keyup.enter="doLogin"></label><div v-if="error" class="form-error">{{error}}</div><button class="primary login-button" @click="doLogin">安全登录 <span>→</span></button></div></section></div><div v-else class="app-shell"><aside><div class="brand"><div class="brand-mark small">VD</div><div><b>VD NEXUS</b><span>{{session.role==='platform_super'?'平台运营后台':'企业管理后台'}}</span></div></div><div class="tenant-chip" v-if="session.role!=='platform_super'"><i></i><div><span>当前企业</span><b>{{session.bootstrap?.organization?.name||`Organization #${session.tenantId}`}}</b><small>{{session.organizationCode}}</small></div></div><nav><span class="nav-label">{{session.role==='platform_super'?'平台管理':'企业运营'}}</span><button v-for="item in nav" :key="item.name" :class="{active:page===item.name}" @click="go(item.name)"><i>{{item.icon}}</i><span>{{item.label}}</span><b>›</b></button></nav><div class="aside-foot"><span class="avatar">{{session.username.slice(0,1).toUpperCase()}}</span><div><b>{{session.username}}</b><small>{{session.role}}</small></div><button title="退出登录" @click="logout">↪</button></div></aside><main><header class="topbar"><div><span class="eyebrow">{{session.role==='platform_super'?'PLATFORM OPERATIONS':'ENTERPRISE OPERATIONS'}}</span><h1>{{title}}</h1></div><div class="top-actions"><span class="system-online"><i></i>安全会话已连接</span><div class="user-mini"><span class="avatar">{{session.username.slice(0,1).toUpperCase()}}</span><div><b>{{session.username}}</b><small>{{session.role}}</small></div></div></div></header><div class="content"><RouterView/></div><nav class="mobile-nav"><button v-for="item in nav.slice(0,4)" :key="item.name" :class="{active:page===item.name}" @click="go(item.name)"><i>{{item.icon}}</i><span>{{item.label}}</span></button></nav></main></div></template>
