<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'

type AnyRow = Record<string, any>
const loggedIn=ref(false), loading=ref(false), section=ref('dashboard'), csrf=ref(''), username=ref('')
const login=reactive({username:'admin',password:''}), error=ref(''), toast=ref('')
const data=ref<any>({}), query=ref(''), statusFilter=ref(''), tierFilter=ref('')
const modal=ref(''), form=reactive<AnyRow>({}), reportDetail=ref<any>(null)
const nav=[['dashboard','工作台','01'],['reports','检查报告','02'],['devices','设备与授权','03'],['codes','激活码','04'],['support','故障处理','05'],['releases','版本发布','06'],['profile','检测规则','07'],['homepage','产品主页','08'],['audit','系统与审计','09']]
const themes=[['obsidian','黑曜石'],['cyber','赛博蓝'],['daylight','极昼浅色']], theme=ref(localStorage.getItem('tk-admin-theme')||'obsidian')
const title=computed(()=>nav.find(x=>x[0]===section.value)?.[1]||'管理中心')
function applyTheme(){document.documentElement.dataset.theme=theme.value;localStorage.setItem('tk-admin-theme',theme.value)}
function cycleTheme(){const i=themes.findIndex(x=>x[0]===theme.value);theme.value=themes[(i+1)%themes.length][0];applyTheme()}

async function api(path:string, options:RequestInit={}){
  const headers=new Headers(options.headers||{}); if(csrf.value&&options.method&&options.method!=='GET')headers.set('X-CSRF-Token',csrf.value)
  if(options.body&&!(options.body instanceof FormData))headers.set('Content-Type','application/json')
  const response=await fetch(path,{credentials:'same-origin',...options,headers}); const body=await response.json().catch(()=>({}))
  if(!response.ok)throw new Error(body.error?.message||body.detail||`请求失败 ${response.status}`); return body
}
function notice(text:string){toast.value=text;setTimeout(()=>toast.value='',2600)}
async function boot(){try{const x=await api('/tk-api/session');loggedIn.value=true;csrf.value=x.csrf;username.value=x.username;await load()}catch{loggedIn.value=false}}
async function doLogin(){error.value='';try{const x=await api('/tk-api/login',{method:'POST',body:JSON.stringify(login)});loggedIn.value=true;csrf.value=x.csrf;username.value=x.username;await load()}catch(e:any){error.value=e.message}}
async function logout(){await api('/tk-api/logout',{method:'POST'});location.reload()}
async function go(name:string){section.value=name;query.value='';statusFilter.value='';tierFilter.value='';await load()}
async function load(){loading.value=true;try{
  const q=encodeURIComponent(query.value)
  if(section.value==='dashboard')data.value=await api('/tk-api/stats')
  else if(section.value==='customers')data.value=await api(`/tk-api/customers?q=${q}`)
  else if(section.value==='rooms')data.value=await api(`/tk-api/rooms?q=${q}`)
  else if(section.value==='devices')data.value=await api(`/tk-api/devices?q=${q}`)
  else if(section.value==='reports')data.value=await api(`/tk-api/reports?q=${q}&status=${statusFilter.value}`)
  else if(section.value==='support')data.value=await api(`/tk-api/support?q=${q}&status=${statusFilter.value}`)
  else if(section.value==='codes')data.value=await api(`/tk-api/codes?q=${q}&status=${statusFilter.value}&tier=${tierFilter.value}`)
  else if(section.value==='releases')data.value=await api('/tk-api/releases')
  else if(section.value==='profile')data.value=await api('/tk-api/profile')
  else if(section.value==='homepage')data.value=await api('/tk-api/homepage')
  else if(section.value==='audit')data.value=await api('/tk-api/audit')
}catch(e:any){notice(e.message)}finally{loading.value=false}}
function openModal(type:string,row:AnyRow={}){modal.value=type;Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,row)}
async function saveCustomer(){await api('/tk-api/customer/save',{method:'POST',body:JSON.stringify({id:form.id||null,name:form.name,contact:form.contact||'',notes:form.notes||'',status:form.status||'active'})});modal.value='';notice('客户已保存');await load()}
async function saveRoom(){await api('/tk-api/room/save',{method:'POST',body:JSON.stringify({id:form.id||null,customer_id:form.customer_id?+form.customer_id:null,name:form.name,region:form.region||'',bitrate_kbps:+(form.bitrate_kbps||6000),notes:form.notes||'',status:form.status||'active'})});modal.value='';notice('直播间已保存');await load()}
async function saveDevice(){await api('/tk-api/device/save',{method:'POST',body:JSON.stringify({device_id:form.device_id,customer_id:form.customer_id?+form.customer_id:null,room_id:form.room_id?+form.room_id:null,status:form.status||'active',notes:form.notes||'',unbind_license:!!form.unbind_license})});modal.value='';notice('设备信息已更新');await load()}
async function saveSupport(){await api('/tk-api/support/save',{method:'POST',body:JSON.stringify({id:form.id||null,report_id:form.report_id||null,device_id:form.device_id||null,title:form.title,status:form.status||'open',owner:form.owner||'',notes:form.notes||''})});modal.value='';notice('故障单已保存');await load()}
async function generateCodes(){const x=await api('/tk-api/codes/generate',{method:'POST',body:JSON.stringify({tier:form.tier||'TK-MONTH',count:+(form.count||1),note:form.note||'',batch:form.batch||''})});form.generated=x.codes.join('\n');notice(`已生成 ${x.codes.length} 个激活码`);await load()}
async function changeCode(code:string,status:string){if(!status)return;await api('/tk-api/codes/status',{method:'POST',body:JSON.stringify({code,status})});notice('状态已更新');await load()}
async function showReport(id:string){reportDetail.value=await api(`/tk-api/report/${id}`);modal.value='report'}
async function saveHomepage(){await api('/tk-api/homepage',{method:'POST',body:JSON.stringify({values:data.value})});notice('产品主页已保存并同步')}
async function publish(){const fd=new FormData();for(const key of ['version','title','notes','details','channel','minimum_version'])fd.append(key,form[key]||'');fd.append('mandatory',form.mandatory?'true':'false');if(form.file)fd.append('file',form.file);await api('/tk-api/release',{method:'POST',body:fd});modal.value='';notice('候选版本已上传，请校验后手动设为当前版本');await load()}
async function activateRelease(version:string){await api('/tk-api/release/activate',{method:'POST',body:JSON.stringify({version})});notice('当前生效版本已切换');await load()}
async function saveProfile(){const p=data.value.profile;await api('/tk-api/profile',{method:'POST',body:JSON.stringify({name:p.name,region:p.region,bitrate_kbps:+p.bitrate_kbps,rules:p.rules})});notice('检测规则已保存并下发');await load()}
watch([statusFilter,tierFilter],()=>{if(['reports','codes'].includes(section.value))load()})
onMounted(()=>{applyTheme();boot()})
</script>

<template>
  <div v-if="!loggedIn" class="login-shell"><div class="login-visual"><div class="login-radar"><i></i><b>LIVE<br>CONTROL</b></div><strong>直播技术准备度<br>运营控制中心</strong><p>检查、授权、故障与版本发布统一管理</p></div><div class="login-card"><button class="login-theme" @click="cycleTheme">{{themes.find(x=>x[0]===theme)?.[1]}}</button><div class="logo">◈</div><div class="login-eyebrow">SECURE OPERATIONS CONSOLE</div><h1>维度 TK 管理中心</h1><p>开播检查、设备授权、故障处理与客户端发布</p><label>管理员账号<input v-model="login.username" autocomplete="username"></label><label>登录密码<input v-model="login.password" type="password" autocomplete="current-password" @keyup.enter="doLogin"></label><div v-if="error" class="error">{{error}}</div><button class="primary full" @click="doLogin">进入管理控制台</button><small><i class="online-dot"></i> 安全会话 · 登录失败自动限流</small></div></div>
  <div v-else class="app-shell">
    <aside><div class="brand"><b>◈ 维度 TK</b><span>直播检测管理平台</span></div><nav><button v-for="item in nav" :class="{active:section===item[0]}" @click="go(item[0])"><i>{{item[2]}}</i>{{item[1]}}</button></nav><div class="aside-foot"><span>{{username}}</span><button @click="cycleTheme">{{themes.find(x=>x[0]===theme)?.[1]}}</button><button @click="logout">退出</button></div></aside>
    <main><header><div><div class="header-eyebrow">WEIDU LIVE OPERATIONS</div><h1>{{title}}</h1><p>V2.5 产品运营中心 · 开播检查、授权与发布统一管理</p></div><div class="header-actions"><span class="system-online"><i></i>系统运行正常</span><a href="/" target="_blank" class="ghost">预览产品主页 ↗</a></div></header>
      <div v-if="loading" class="loading">正在加载数据…</div>
      <template v-else>
        <section v-if="section==='dashboard'">
          <article class="ops-hero"><div><span>LIVE READINESS COMMAND</span><h2>直播开播技术准备度总览</h2><p>集中查看今日检测、阻断问题、修复效果、授权状态和客户端发布情况。</p><div class="ops-actions"><button class="primary" @click="go('reports')">查看检查报告</button><button @click="go('support')">处理异常故障</button></div></div><div class="ops-core"><div class="ops-ring r1"></div><div class="ops-ring r2"></div><b>TK<br><small>CORE</small></b><em>V{{data.active_release?.version||'--'}}</em></div></article>
          <div class="metrics"><div v-for="m in [['今日检查',data.reports_today],['可以开播',data.readiness?.READY],['存在风险',data.readiness?.READY_WITH_RISK],['不建议开播',data.readiness?.NOT_READY],['今日下载',data.downloads_today],['待处理',data.support_open]]" class="metric"><span>{{m[0]}}</span><b>{{m[1]||0}}</b></div></div>
          <div class="dash-grid"><article class="panel command-panel"><h3>双模式运行分布</h3><div class="mode-orbit"><div><strong>{{data.run_modes?.daily_preflight||0}}</strong><span>日常开播检查</span></div><i>LIVE<br>CORE</i><div><strong>{{data.run_modes?.environment_setup||0}}</strong><span>环境配置任务</span></div></div></article><article class="panel"><h3>今日检查结果</h3><div class="status-row pass"><span>通过 PASS</span><b>{{data.report_statuses?.PASS||0}}</b></div><div class="status-row warning"><span>风险 WARNING</span><b>{{data.report_statuses?.WARNING||0}}</b></div><div class="status-row fail"><span>失败 FAIL</span><b>{{data.report_statuses?.FAIL||0}}</b></div></article><article class="panel"><h3>常见失败项目</h3><div v-for="x in data.top_faults" class="list-row"><span>{{x.title}}</span><b>{{x.count}} 次</b></div><p v-if="!data.top_faults?.length" class="muted">暂无失败数据</p></article><article class="panel"><h3>客户端版本分布</h3><div v-for="x in data.versions" class="list-row"><span>V{{x.app_version||'未知'}}</span><b>{{x.count}} 台</b></div></article><article class="panel"><h3>当前正式版本</h3><div class="release-big">V{{data.active_release?.version||'尚未发布'}}</div><p class="muted">{{data.active_release?.title||'请在版本发布中上传候选安装包'}}</p></article></div>
        </section>
        <section v-if="['customers','rooms','devices'].includes(section)"><div class="toolbar"><input v-model="query" placeholder="搜索名称、联系方式或备注" @keyup.enter="load"><button @click="load">搜索</button><button v-if="section==='customers'" class="primary" @click="openModal('customer')">新增客户</button><button v-if="section==='rooms'" class="primary" @click="openModal('room')">新增直播间</button></div>
          <div class="table-wrap"><table v-if="section==='customers'"><thead><tr><th>客户</th><th>联系方式</th><th>直播间</th><th>状态</th><th>备注</th><th></th></tr></thead><tbody><tr v-for="x in data.customers"><td><b>{{x.name}}</b></td><td>{{x.contact||'-'}}</td><td>{{x.room_count}}</td><td><span class="pill">{{x.status}}</span></td><td>{{x.notes||'-'}}</td><td><button @click="openModal('customer',x)">编辑</button></td></tr></tbody></table>
          <table v-if="section==='rooms'"><thead><tr><th>直播间</th><th>客户</th><th>地区</th><th>码率</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="x in data.rooms"><td><b>{{x.name}}</b></td><td>{{x.customer||'-'}}</td><td>{{x.region||'-'}}</td><td>{{x.bitrate_kbps}} Kbps</td><td><span class="pill">{{x.status}}</span></td><td><button @click="openModal('room',x)">编辑</button></td></tr></tbody></table>
          <table v-if="section==='devices'"><thead><tr><th>设备编号</th><th>当前检测地区</th><th>版本</th><th>授权</th><th>最后在线</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="x in data.devices"><td class="mono">{{x.device_id}}</td><td>{{x.target_region_id||'未选择'}}</td><td>V{{x.app_version||'-'}}</td><td class="mono">{{x.license_code||'免费体验'}}</td><td>{{x.last_seen?.replace('T',' ').slice(0,19)}}</td><td><span class="pill">{{x.status}}</span></td><td><button @click="openModal('device',x)">管理</button></td></tr></tbody></table></div></section>
        <section v-if="section==='reports'"><div class="toolbar"><select v-model="statusFilter"><option value="">全部结论</option><option value="READY">可以开播</option><option value="READY_WITH_RISK">存在风险</option><option value="NOT_READY">不建议开播</option><option value="INCOMPLETE">检测未完成</option></select><input v-model="query" placeholder="目标地区或设备编号" @keyup.enter="load"><button @click="load">筛选</button><a class="button" href="/tk-api/reports/export">导出 CSV</a></div><div class="table-wrap"><table><thead><tr><th>检查时间</th><th>运行模式</th><th>目标地区</th><th>设备</th><th>报告版本</th><th>开播结论</th><th>说明</th><th></th></tr></thead><tbody><tr v-for="x in data.reports"><td>{{x.checked_at?.replace('T',' ').slice(0,19)}}</td><td><span :class="['mode-pill',x.run_mode]">{{x.run_mode==='environment_setup'?'环境配置':'日常检查'}}</span></td><td><b>{{x.target_region_id}}</b></td><td class="mono">{{x.device_id}}</td><td>Schema V{{x.schema_version}}</td><td><span :class="['pill',x.overall_status.toLowerCase()]">{{x.readiness_level||x.overall_status}}</span></td><td>{{x.conclusion}}</td><td><button @click="showReport(x.report_id)">查看完整证据</button></td></tr></tbody></table></div></section>
        <section v-if="section==='support'"><div class="toolbar"><select v-model="statusFilter"><option value="">全部状态</option><option value="open">待处理</option><option value="processing">处理中</option><option value="resolved">已解决</option><option value="closed">已关闭</option></select><input v-model="query" placeholder="故障标题、设备或处理记录" @keyup.enter="load"><button @click="load">筛选</button><button class="primary" @click="openModal('support',{status:'open'})">新增故障单</button></div><div class="table-wrap"><table><thead><tr><th>故障标题</th><th>设备 / 报告</th><th>状态</th><th>负责人</th><th>更新时间</th><th>处理记录</th><th></th></tr></thead><tbody><tr v-for="x in data.support"><td><b>{{x.title}}</b></td><td class="mono">{{x.device_id||'-'}}<small>{{x.report_id||''}}</small></td><td><span class="pill">{{x.status}}</span></td><td>{{x.owner||'-'}}</td><td>{{x.updated_at?.replace('T',' ').slice(0,19)}}</td><td>{{x.notes||'-'}}</td><td><button @click="openModal('support',x)">处理</button></td></tr></tbody></table></div></section>
        <section v-if="section==='codes'"><div class="code-layout"><article class="panel form"><h3>批量生成时间授权</h3><p class="muted">有效期内不限检测次数，旧次数卡仅用于兼容历史客户。</p><label>授权套餐<select v-model="form.tier"><option>TK-MONTH</option><option>TK-QUARTER</option><option>TK-HALF-YEAR</option><option>TK-YEAR</option></select></label><label>生成数量<input v-model="form.count" type="number" min="1" max="500"></label><label>批次名称<input v-model="form.batch" placeholder="例如 2026-直播工作室"></label><label>客户或备注<input v-model="form.note"></label><button class="primary" @click="generateCodes">立即生成</button><textarea v-if="form.generated" v-model="form.generated" rows="7" readonly></textarea></article><article class="panel"><div class="toolbar"><select v-model="statusFilter"><option value="">全部状态</option><option value="available">未使用</option><option value="distributed">已分发</option><option value="used">已激活</option><option value="exhausted">已耗尽</option><option value="expired">已过期</option><option value="revoked">已作废</option></select><select v-model="tierFilter"><option value="">全部套餐</option><option>TK-MONTH</option><option>TK-QUARTER</option><option>TK-HALF-YEAR</option><option>TK-YEAR</option><option>TK1</option><option>TKX</option><option>TKV</option></select><input v-model="query" placeholder="搜索激活码、批次或备注" @keyup.enter="load"><a class="button" href="/tk-api/codes/export">导出</a></div><div class="table-wrap compact"><table><thead><tr><th>激活码</th><th>套餐</th><th>有效期</th><th>状态</th><th>绑定设备</th><th>批次 / 备注</th><th>操作</th></tr></thead><tbody><tr v-for="x in data.codes"><td class="mono">{{x.code}}</td><td><b>{{x.plan_code||x.tier}}</b></td><td>{{x.expires_at?x.expires_at.replace('T',' ').slice(0,16):(x.credits<0?'永久':x.credits+'次')}}</td><td><span class="pill">{{x.status}}</span></td><td class="mono">{{x.bound_device_id||'-'}}</td><td>{{x.batch||'-'}}<small>{{x.customer_note}}</small></td><td><select @change="changeCode(x.code,($event.target as HTMLSelectElement).value)"><option value="">切换状态</option><option value="distributed">已分发</option><option value="available">未使用</option><option value="expired">已过期</option><option value="revoked">作废</option></select></td></tr></tbody></table></div></article></div></section>
        <section v-if="section==='releases'"><div class="toolbar"><button class="primary" @click="openModal('release',{channel:'stable'})">发布新版本</button></div><div class="release-grid"><article v-for="x in data.releases" class="panel release-card"><div><span :class="['pill',x.active?'pass':'']">{{x.active?'当前生效':'历史版本'}}</span><span class="pill">{{x.channel}}</span></div><h2>V{{x.version}}</h2><h3>{{x.title}}</h3><p>{{x.notes}}</p><small>大小 {{(x.file_size/1048576).toFixed(1)}} MB · SHA-256</small><code>{{x.sha256}}</code><button v-if="!x.active" @click="activateRelease(x.version)">回滚到此版本</button></article><div v-if="!data.releases?.length" class="empty">尚未发布版本</div></div></section>
        <section v-if="section==='profile'&&data.profile"><article class="panel form settings"><h3>客户端检测阈值</h3><p class="muted">客户端联网检查前读取当前规则。修改后请先在测试直播间验证。</p><label>规则名称<input v-model="data.profile.name"></label><label>适用地区<input v-model="data.profile.region"></label><label>基准码率 Kbps<input v-model="data.profile.bitrate_kbps" type="number"></label><div class="profile-grid"><label>上传倍数<input v-model="data.profile.rules.upload_multiplier" type="number" step="0.1"></label><label>上传测试字节<input v-model="data.profile.rules.upload_test_bytes" type="number"></label><label>丢包风险 %<input v-model="data.profile.rules.packet_loss_warning" type="number" step="0.1"></label><label>丢包失败 %<input v-model="data.profile.rules.packet_loss_fail" type="number" step="0.1"></label><label>抖动风险 ms<input v-model="data.profile.rules.jitter_warning_ms" type="number"></label><label>抖动失败 ms<input v-model="data.profile.rules.jitter_fail_ms" type="number"></label><label>延迟风险 ms<input v-model="data.profile.rules.latency_warning_ms" type="number"></label><label>延迟失败 ms<input v-model="data.profile.rules.latency_fail_ms" type="number"></label><label>最低磁盘空间 GB<input v-model="data.profile.rules.min_free_disk_gb" type="number"></label></div><button class="primary" @click="saveProfile">保存并下发规则</button></article></section>
        <section v-if="section==='homepage'"><article class="panel form settings"><h3>旗舰产品主页</h3><p class="muted">只编辑真实产品资料。页面布局、品牌视觉、隐私边界和免责声明由系统保护。</p><label>产品名称<input v-model="data.product_name"></label><label>首屏主标题<input v-model="data.home_hero_title"></label><label>首屏副标题<textarea v-model="data.home_hero_subtitle" rows="2"></textarea></label><label>产品介绍<textarea v-model="data.product_intro" rows="4"></textarea></label><label>日常开播检查说明<textarea v-model="data.home_daily_text" rows="3"></textarea></label><label>一键配置环境说明<textarea v-model="data.home_setup_text" rows="3"></textarea></label><label>七组功能（每行一项）<textarea v-model="data.product_features" rows="7"></textarea></label><label>处理流程（每行一项）<textarea v-model="data.home_steps" rows="5"></textarea></label><label>使用说明与常见问题<textarea v-model="data.product_faq" rows="6"></textarea></label><label>系统要求<textarea v-model="data.home_system_requirements" rows="2"></textarea></label><label>补充提示<textarea v-model="data.home_extra_notice" rows="3"></textarea></label><label>客服说明<textarea v-model="data.support_text" rows="3"></textarea></label><label>最新更新说明<textarea v-model="data.latest_changelog" rows="5"></textarea></label><div class="toolbar"><button class="primary" @click="saveHomepage">保存并同步主页</button><a class="button" href="/" target="_blank">预览主页</a></div></article></section>
        <section v-if="section==='audit'"><div class="table-wrap"><table><thead><tr><th>时间</th><th>管理员</th><th>操作</th><th>对象</th><th>详情</th></tr></thead><tbody><tr v-for="x in data.audit"><td>{{x.created_at?.replace('T',' ').slice(0,19)}}</td><td>{{x.actor}}</td><td><b>{{x.action}}</b></td><td>{{x.target_type}} {{x.target_id}}</td><td>{{x.details}}</td></tr></tbody></table></div></section>
      </template>
    </main>
    <div v-if="toast" class="toast">{{toast}}</div>
    <div v-if="modal" class="modal-mask" @click.self="modal=''" role="dialog"><div class="modal"><button class="close" @click="modal=''">×</button>
      <div v-if="modal==='customer'" class="form"><h2>{{form.id?'编辑':'新增'}}客户</h2><label>客户名称<input v-model="form.name"></label><label>联系方式<input v-model="form.contact"></label><label>状态<select v-model="form.status"><option value="active">正常</option><option value="inactive">停用</option></select></label><label>备注<textarea v-model="form.notes" rows="4"></textarea></label><button class="primary" @click="saveCustomer">保存客户</button></div>
      <div v-if="modal==='room'" class="form"><h2>{{form.id?'编辑':'新增'}}直播间</h2><label>客户编号<input v-model="form.customer_id" type="number"></label><label>直播间名称<input v-model="form.name"></label><label>目标地区<input v-model="form.region"></label><label>码率 Kbps<input v-model="form.bitrate_kbps" type="number"></label><label>备注<textarea v-model="form.notes"></textarea></label><button class="primary" @click="saveRoom">保存直播间</button></div>
      <div v-if="modal==='device'" class="form"><h2>管理设备</h2><label>设备编号<input v-model="form.device_id" readonly></label><label>客户编号<input v-model="form.customer_id" type="number"></label><label>直播间编号<input v-model="form.room_id" type="number"></label><label>状态<select v-model="form.status"><option value="active">正常</option><option value="inactive">停用</option></select></label><label>备注<textarea v-model="form.notes"></textarea></label><label class="check"><input v-model="form.unbind_license" type="checkbox"> 解除当前激活码绑定</label><button class="primary" @click="saveDevice">保存设备</button></div>
      <div v-if="modal==='support'" class="form"><h2>{{form.id?'处理':'新增'}}故障单</h2><label>故障标题<input v-model="form.title"></label><label>设备编号<input v-model="form.device_id"></label><label>报告编号<input v-model="form.report_id"></label><label>状态<select v-model="form.status"><option value="open">待处理</option><option value="processing">处理中</option><option value="resolved">已解决</option><option value="closed">已关闭</option></select></label><label>负责人<input v-model="form.owner"></label><label>处理记录<textarea v-model="form.notes" rows="6"></textarea></label><button class="primary" @click="saveSupport">保存故障单</button></div>
      <div v-if="modal==='release'" class="form"><h2>发布客户端版本</h2><label>版本号<input v-model="form.version" placeholder="2.5.0"></label><label>更新标题<input v-model="form.title"></label><label>更新摘要<textarea v-model="form.notes"></textarea></label><label>详细更新内容<textarea v-model="form.details" rows="6"></textarea></label><label>最低兼容版本<input v-model="form.minimum_version"></label><label>发布通道<select v-model="form.channel"><option value="stable">正式版</option><option value="beta">测试版</option></select></label><label class="check"><input v-model="form.mandatory" type="checkbox"> 强制更新</label><label>安装程序<input type="file" accept=".exe" @change="form.file=($event.target as HTMLInputElement).files?.[0]"></label><button class="primary" @click="publish">上传为待发布版本</button></div>
      <div v-if="modal==='report'&&reportDetail" class="report-detail"><h2>开播环境检查报告</h2><div class="report-head"><b :class="reportDetail.report.overall_status.toLowerCase()">{{reportDetail.report.readiness_level||reportDetail.report.overall_status}}</b><span>{{reportDetail.report.conclusion}}</span><span :class="['mode-pill',reportDetail.report.run_mode]">{{reportDetail.report.run_mode==='environment_setup'?'环境配置':'日常检查'}}</span><span class="pill">{{reportDetail.report.target_region_id}}</span></div><div v-if="reportDetail.report.run_mode==='environment_setup'" class="setup-compare"><article><label>配置前快照</label><code>{{JSON.stringify(reportDetail.report.before_snapshot,null,2)}}</code></article><article><label>配置后快照</label><code>{{JSON.stringify(reportDetail.report.after_snapshot,null,2)}}</code></article></div><div class="report-grid"><article v-for="x in reportDetail.items" :class="['report-item',x.status.toLowerCase()]"><div class="report-item-head"><span :class="['pill',x.status.toLowerCase()]">{{x.priority||x.status}}</span><b>{{x.title}}</b><strong>{{x.value}}</strong></div><p><label>检测证据</label><span v-for="line in x.evidence">{{line}}</span></p><p><label>问题定位</label>{{x.diagnosis||x.reason}}</p><p class="impact"><label>不处理的影响</label>{{x.impact||'当前未发现明确影响'}}</p><p><label>处理步骤</label><span v-for="(line,i) in x.solutions">{{i+1}}. {{line}}</span><span v-if="!x.solutions?.length">当前无需处理</span></p><footer>数据来源：{{x.data_source}} · 置信度：{{x.confidence}} · 耗时 {{x.duration_ms||0}}ms <em v-if="x.repairable">可由客户端处理</em></footer></article></div></div>
    </div></div>
  </div>
</template>
