server {
    listen 80;
    listen [::]:80;
    server_name tk.wdai.cc;

    root /www/wwwroot/tk.wdai.cc;
    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        try_files $uri =404;
    }
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name tk.wdai.cc;

    ssl_certificate /etc/letsencrypt/live/tk.wdai.cc/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tk.wdai.cc/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:TKSSL:10m;
    ssl_session_timeout 1d;

    client_max_body_size 550m;

    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy same-origin always;
    add_header Strict-Transport-Security "max-age=31536000" always;

    location /downloads/ {
        alias /opt/tk-platform/runtime/downloads/;
        default_type application/octet-stream;
        add_header Content-Disposition "attachment";
        add_header X-Content-Type-Options nosniff always;
    }

    location / {
        proxy_pass http://127.0.0.1:18080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
}

