<script setup lang="ts">
import{computed,onMounted,ref}from'vue';import{session}from'../api';import{enterpriseApi}from'../services/enterprise';import StatusPill from'../components/StatusPill.vue'
const devices=ref<any[]>([]),loading=ref(true),error=ref(''),detail=ref<any>(null),severity=ref('');const minimum=computed(()=>session.bootstrap?.features?.device_center?.minimum_version||session.bootstrap?.minimum_version||'2.1.0')
const incidents=computed(()=>{const rows:any[]=[];for(const d of devices.value){for(const reason of d.abnormal_reasons||[])rows.push({...reason,device_id:d.device_id,device_name:d.display_name,last_heartbeat_at:d.last_heartbeat_at,online_state:d.online_state,studio_state:d.studio_state,collector_state:d.collector_state,metrics:d.metrics,agent_version:d.agent_version});if(d.agent_version&&minimum.value&&d.agent_version.localeCompare(minimum.value,undefined,{numeric:true})<0)rows.push({code:'CLIENT_VERSION_OUTDATED',level:'warning',message:'客户端版本过旧',device_id:d.device_id,device_name:d.display_name,last_heartbeat_at:d.last_heartbeat_at,agent_version:d.agent_version})}return severity.value?rows.filter(x=>x.level===severity.value):rows})
const meta:any={DEVICE_OFFLINE:{cause:'客户端、电脑电源或网络连接中断',impact:'无法确认设备当前环境与开播状态',advice:'确认电脑在线、客户端运行且未进入睡眠'},HEARTBEAT_UNSTABLE:{cause:'心跳延迟或网络波动',impact:'实时状态存在延迟',advice:'检查本地网络和客户端后台运行状态'},LIVE_SOFTWARE_NOT_RUNNING:{cause:'TikTok LIVE Studio 进程未运行',impact:'当前电脑尚未进入直播软件准备状态',advice:'在现场电脑启动并确认正确的 LIVE Studio 程序'},COLLECTOR_UNHEALTHY:{cause:'客户端采集服务未成功上报',impact:'CPU、内存和网络指标可能过期',advice:'打开客户端帮助与诊断并执行重新同步'},NETWORK_LATENCY_HIGH:{cause:'设备到服务端的轻量网络采样延迟偏高',impact:'推流稳定性可能降低',advice:'检查 Wi-Fi 干扰、本地出口和目标地区线路'},UPLOAD_BANDWIDTH_LOW:{cause:'最近上传承载能力低于直播通用基线',impact:'高码率推流可能卡顿',advice:'减少上行占用并排查运营商线路'},CLIENT_VERSION_OUTDATED:{cause:'客户端低于平台最低版本',impact:'新配置或修复能力可能不可用',advice:'在客户端帮助与诊断中检查更新'}}
async function load(){loading.value=true;error.value='';try{devices.value=(await enterpriseApi.devices(new URLSearchParams({limit:'200',sort:'abnormal'}))).items||[]}catch(e:any){error.value=`${e.message}${e.requestId?`（请求编号 ${e.requestId}）`:''}`}finally{loading.value=false}}
onMounted(load)
</script>
<template><div class="page-stack"><section class="panel"><header class="panel-head"><div><span class="eyebrow">INCIDENT CENTER</span><h2>异常处理</h2><p>依据设备最新心跳形成即时异常视图；恢复后会在下一次刷新自动消失。</p></div><div class="action-cluster"><select v-model="severity"><option value="">全部级别</option><option value="critical">严重</option><option value="warning">警告</option><option value="info">提示</option></select><button @click="load">刷新状态</button></div></header><div v-if="error" class="state-panel error"><span class="state-icon">!</span><h3>异常视图暂时不可用</h3><p>{{error}}</p><button class="primary" @click="load">重新加载</button></div><div v-else-if="loading" class="skeleton-table"><i v-for="n in 6" class="skeleton"></i></div><div v-else-if="!incidents.length" class="empty-state success-empty"><b>当前没有匹配的实时异常</b><p>设备离线、直播软件、采集、版本、延迟和上传风险均未触发。</p></div><div v-else class="incident-grid"><article v-for="x in incidents" :class="x.level" @click="detail=x"><span class="incident-symbol">!</span><div><header><b>{{x.message}}</b><span :class="['source-chip',x.level==='critical'?'disabled':x.level==='warning'?'trial':'default']">{{x.level}}</span></header><p>{{x.device_name}} · {{x.device_id}}</p><small>{{meta[x.code]?.impact||'设备状态需要进一步检查'}}</small></div><button>查看根因 →</button></article></div></section><div v-if="detail" class="modal-mask" @click.self="detail=null"><article class="incident-modal"><header><div><span class="eyebrow">{{detail.code}}</span><h2>{{detail.message}}</h2><p>{{detail.device_name}} · {{detail.device_id}}</p></div><button class="drawer-close" @click="detail=null">×</button></header><div class="incident-state"><StatusPill :value="detail.online_state||'warning'"/><StatusPill :value="detail.studio_state||'unknown'"/><StatusPill :value="detail.collector_state||'unknown'"/></div><dl><div><dt>问题</dt><dd>{{detail.message}}</dd></div><div><dt>原因</dt><dd>{{meta[detail.code]?.cause||'需要结合客户端诊断进一步确认'}}</dd></div><div><dt>系统检查</dt><dd>设备心跳、LIVE Studio 进程、采集健康、客户端版本和轻量网络指标</dd></div><div><dt>影响</dt><dd>{{meta[detail.code]?.impact||'可能影响企业对设备状态的准确判断'}}</dd></div><div><dt>建议</dt><dd>{{meta[detail.code]?.advice||'在现场客户端执行帮助与诊断流程'}}</dd></div><div><dt>恢复状态</dt><dd>等待下一次有效心跳自动复核；本页面不会远程执行系统命令</dd></div><div><dt>技术详情</dt><dd>版本 {{detail.agent_version||'-'}} · 最后心跳 {{detail.last_heartbeat_at?.replace('T',' ').slice(0,19)||'无'}}</dd></div></dl><footer><button class="primary" @click="detail=null">我已了解</button></footer></article></div></div></template>
