<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { api, session } from '../api'
import StatusPill from '../components/StatusPill.vue'
const data=ref<any[]>([]),q=ref(''),code=ref(''),expires=ref(''),detail=ref<any>(null),saving=ref(false)
const canEdit=session.permissions.includes('devices.manage')
const form=reactive<any>({display_name:'',room_id:null,streaming_account_id:null,store_name:'',location:'',owner_name:'',tags_text:''})
async function load(){data.value=(await api(`/tk-api/enterprise/devices?q=${encodeURIComponent(q.value)}`)).devices}
async function bind(){const x=await api('/tk-api/enterprise/binding-codes',{method:'POST',body:'{}'});code.value=x.code;expires.value=x.expires_at}
async function openDevice(id:string){detail.value=await api(`/tk-api/enterprise/devices/${id}`);const d=detail.value.device;Object.assign(form,{display_name:d.display_name,room_id:d.room_id,streaming_account_id:d.streaming_account_id,store_name:d.store_name,location:d.location,owner_name:d.owner_name,tags_text:(d.tags||[]).join('、')})}
async function save(){saving.value=true;try{await api(`/tk-api/enterprise/devices/${detail.value.device.device_id}`,{method:'POST',body:JSON.stringify({...form,tags:form.tags_text.split(/[,，、]/).map((x:string)=>x.trim()).filter(Boolean),tags_text:undefined})});await openDevice(detail.value.device.device_id);await load()}finally{saving.value=false}}
onMounted(load)
</script>
<template><section class="panel"><header class="panel-head"><div><span class="eyebrow">DEVICE FLEET</span><h2>企业设备管理</h2><p>实时状态、历史事件、检测报告和故障告警集中查看。</p></div><button v-if="canEdit" class="primary" @click="bind">生成设备绑定码</button></header><div v-if="code" class="binding-code"><span>10分钟内在客户端“设置”中输入</span><strong>{{code}}</strong><small>{{expires}}</small></div><div class="toolbar"><input v-model="q" placeholder="搜索电脑、门店或负责人" @keyup.enter="load"><button @click="load">搜索</button></div><div class="responsive-table"><table><thead><tr><th>设备</th><th>在线</th><th>开播准备度</th><th>LIVE Studio</th><th>地区</th><th>最后心跳</th><th></th></tr></thead><tbody><tr v-for="d in data"><td><b>{{d.display_name}}</b><small>{{d.device_id}}</small></td><td><StatusPill :value="d.online"/></td><td><StatusPill :value="d.readiness_state"/></td><td><StatusPill :value="d.studio_state"/></td><td>{{d.target_region_id}}</td><td>{{d.last_heartbeat_at?.replace('T',' ').slice(0,19)||'尚未上报'}}</td><td><button class="text-button" @click="openDevice(d.device_id)">查看详情</button></td></tr></tbody></table></div></section>
<div v-if="detail" class="drawer-mask" @click.self="detail=null"><aside class="detail-drawer"><header><div><span class="eyebrow">DEVICE INTELLIGENCE</span><h2>{{detail.device.display_name}}</h2><small>{{detail.device.device_id}}</small></div><button class="drawer-close" @click="detail=null">×</button></header><div class="drawer-status"><StatusPill :value="detail.device.online"/><StatusPill :value="detail.device.readiness_state"/><StatusPill :value="detail.device.studio_state"/></div><form v-if="canEdit" class="drawer-form" @submit.prevent="save"><label>设备名称<input v-model="form.display_name"></label><label>门店/小组<input v-model="form.store_name"></label><label>位置<input v-model="form.location"></label><label>负责人<input v-model="form.owner_name"></label><label class="wide">标签<input v-model="form.tags_text" placeholder="多个标签用顿号分隔"></label><button class="primary" :disabled="saving">{{saving?'保存中…':'保存设备资料'}}</button></form><section class="drawer-section"><h3>三类环境摘要</h3><div class="summary-grid"><article v-for="(value,key) in detail.device.module_summary"><span>{{key}}</span><b>{{value.status}}</b><small>{{value.issues||0}} 个问题</small></article></div></section><section class="drawer-section"><h3>设备时间线</h3><div class="timeline"><article v-for="x in detail.events"><i></i><div><b>{{x.event_type}}</b><p>{{x.client_at||x.created_at}}</p></div><StatusPill :value="x.severity"/></article><div v-if="!detail.events.length" class="empty-state">暂无设备事件</div></div></section><section class="drawer-section"><h3>最近检测报告</h3><article class="mini-report" v-for="x in detail.reports"><div><b>{{x.conclusion}}</b><small>{{x.checked_at}}</small></div><StatusPill :value="x.readiness_level==='READY'?'ready':x.readiness_level==='NOT_READY'?'blocked':'warning'"/></article></section></aside></div></template>
