<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{platformApi}from'../services/platform'
const organizations=ref<any[]>([]),devices=ref<any[]>([]),rows=ref<any[]>([]),data=ref<any>(null),organizationId=ref(''),deviceId=ref(''),baseline=ref(''),loading=ref(true),saving=ref(false),error=ref(''),notice=ref('');const filters=reactive({keyword:'',agent_version:''})
const dirty=computed(()=>JSON.stringify(rows.value)!==baseline.value)
async function boot(){try{organizations.value=(await platformApi.organizations()).tenants||[];if(organizations.value.length){organizationId.value=String(organizations.value[0].id);await loadDevices()}}catch(e:any){error.value=e.message;loading.value=false}}
async function loadDevices(){loading.value=true;error.value='';deviceId.value='';rows.value=[];try{const params=new URLSearchParams({organization_id:organizationId.value,limit:'200'});if(filters.keyword)params.set('keyword',filters.keyword);if(filters.agent_version)params.set('agent_version',filters.agent_version);devices.value=(await platformApi.devices(params)).items||[];if(devices.value.length){deviceId.value=devices.value[0].device_id;await loadFeatures()}}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function loadFeatures(){if(!deviceId.value)return;loading.value=true;error.value='';notice.value='';try{data.value=await platformApi.deviceFeatures(deviceId.value);rows.value=Object.entries(data.value.features).map(([code,value])=>{const x:any=value,o=x.override;return{code,name:x.name,mode:o?(o.enabled?'enabled':'disabled'):'inherit',reason:o?.reason||'',expires_at:o?.expires_at?String(o.expires_at).slice(0,16):'',configText:JSON.stringify(o?.config||{},null,2),effective:x.enabled,source:x.source,rollout:x.rollout}});baseline.value=JSON.stringify(rows.value)}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function save(){if(!dirty.value)return;const original=JSON.parse(baseline.value),changed=rows.value.filter((x,i)=>JSON.stringify(x)!==JSON.stringify(original[i]));if(!window.confirm(`设备覆盖优先于企业和套餐配置。确认修改 ${changed.length} 项吗？`))return;saving.value=true;try{for(const x of changed.filter(x=>x.mode==='inherit'))if(original.find((o:any)=>o.code===x.code)?.mode!=='inherit')await platformApi.clearDeviceFeature(deviceId.value,x.code);const items=changed.filter(x=>x.mode!=='inherit').map(x=>{let config={};try{config=JSON.parse(x.configText||'{}')}catch{throw new Error(`${x.name} 的配置 JSON 无效`)}return{feature_code:x.code,enabled:x.mode==='enabled',reason:x.reason||'平台设备级覆盖',expires_at:x.expires_at||null,config}});if(items.length)await platformApi.saveDeviceFeatures(deviceId.value,items);await loadFeatures();notice.value='设备覆盖已保存，该设备将在下一次 Bootstrap 同步后应用。'}catch(e:any){error.value=`保存失败：${e.message}。请检查原因、过期时间和配置格式。`}finally{saving.value=false}}
async function clearRow(x:any){if(x.mode==='inherit'||!window.confirm(`清除 ${x.name} 的设备覆盖？`))return;try{await platformApi.clearDeviceFeature(deviceId.value,x.code);await loadFeatures();notice.value=`已清除 ${x.name} 的设备覆盖。`}catch(e:any){error.value=e.message}}
onMounted(boot)
</script>
<template><div class="page-stack"><section class="panel"><header class="panel-head"><div><span class="eyebrow">DEVICE OVERRIDES</span><h2>设备功能灰度</h2><p>用于单机验证、临时关闭和定向开放；所有覆盖必须填写原因和有效期。</p></div><div class="action-cluster"><span v-if="dirty" class="dirty-badge">有未保存变化</span><button :disabled="!dirty" @click="loadFeatures">恢复</button><button class="primary" :disabled="!dirty||saving" @click="save">{{saving?'保存中…':'保存设备覆盖'}}</button></div></header><div class="filter-grid"><select v-model="organizationId" @change="loadDevices"><option value="" disabled>选择企业</option><option v-for="x in organizations" :value="String(x.id)">{{x.name}}</option></select><input v-model="filters.keyword" placeholder="搜索设备名称或编号"><input v-model="filters.agent_version" placeholder="客户端版本"><button @click="loadDevices">查询设备</button><select v-model="deviceId" @change="loadFeatures"><option value="" disabled>选择设备</option><option v-for="x in devices" :value="x.device_id">{{x.display_name}} · V{{x.agent_version||'-'}}</option></select></div><div v-if="data" class="selection-summary"><div><span>当前设备</span><b>{{data.device.display_name}}</b><small>{{data.device.device_id}}</small></div><div><span>企业</span><b>#{{data.device.organization_id}}</b></div><div><span>客户端</span><b>V{{data.device.agent_version||'-'}}</b></div><div><span>配置版本</span><b>{{data.config_version}}</b></div></div><div v-if="notice" class="success-banner">{{notice}}</div><div v-if="error" class="state-inline error"><b>设备灰度配置未完成</b><span>{{error}}</span><button @click="loadFeatures">重新加载</button></div><div v-else-if="loading" class="skeleton-table"><i v-for="n in 5" class="skeleton"></i></div><div v-else-if="!deviceId" class="empty-state"><b>没有匹配设备</b><p>调整企业、关键字或版本筛选后重试。</p></div><div v-else class="entitlement-editor"><article v-for="x in rows" :key="x.code"><header><div><b>{{x.name}}</b><small>{{x.code}}</small></div><div class="chip-row"><span :class="['source-chip',x.effective?'enabled':'disabled']">最终{{x.effective?'启用':'关闭'}} · {{x.source}}</span><span v-if="x.rollout?.applied" :class="['source-chip',x.rollout.matched?'enabled':'disabled']">灰度{{x.rollout.matched?'命中':'未命中'}}</span></div></header><div class="entitlement-fields device-override-fields"><label>设备策略<select v-model="x.mode"><option value="inherit">不覆盖</option><option value="enabled">强制启用</option><option value="disabled">强制关闭</option></select></label><label>过期时间<input v-model="x.expires_at" :disabled="x.mode==='inherit'" type="datetime-local"></label><label class="wide">覆盖原因<input v-model="x.reason" :disabled="x.mode==='inherit'" placeholder="必填：测试目的、负责人或故障编号"></label><label class="wide">配置 JSON<textarea v-model="x.configText" :disabled="x.mode==='inherit'" rows="2" spellcheck="false"></textarea></label></div><footer><span>设备覆盖会绕过套餐与企业灰度，但不能绕过平台停用和最低版本。</span><button class="text-button" :disabled="x.mode==='inherit'" @click="clearRow(x)">清除覆盖</button></footer></article></div></section></div></template>
