<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,ref} from 'vue';import {api,session} from '../api';import MetricCard from '../components/MetricCard.vue';import StatusPill from '../components/StatusPill.vue'
const data=ref<any>({metrics:{},devices:[],subscription:{}}),connected=ref(false),updated=ref(''),source=ref<EventSource|null>(null),poll=ref<number>(),reconnect=ref<number>()
const onlineRate=computed(()=>data.value.metrics.devices?Math.round(data.value.metrics.online/data.value.metrics.devices*100):0)
const roleTitle=computed(()=>session.role==='owner'?'企业经营概览':session.role==='operator'?'实时直播与异常提示':session.role==='viewer'?'只读工作台':'设备健康与待处理事项')
async function load(){if(session.enterpriseToken){const response=await api('/api/v2/organization/devices');const devices=response.items||[];data.value={metrics:{devices:devices.length,online:devices.filter((x:any)=>x.online_state==='online').length,ready:devices.filter((x:any)=>x.online_state==='online'&&x.collector_state==='healthy').length,blocked:devices.filter((x:any)=>x.collector_state==='interrupted').length,network_risk:devices.filter((x:any)=>Number(x.metrics?.network_latency_ms||0)>100).length,studio_running:devices.filter((x:any)=>x.studio_state==='running').length,open_alerts:0},subscription:{device_limit:session.bootstrap?.limits?.max_devices},devices:devices.map((x:any)=>({...x,online:x.online_state==='online',readiness_state:x.collector_state==='interrupted'?'blocked':x.online_state==='online'?'ready':'warning',target_region_id:x.binding?`直播间 #${x.binding.room_id}`:'未绑定'}))}}else data.value=await api('/tk-api/enterprise/overview');updated.value=new Date().toLocaleTimeString()}
function stopPoll(){if(poll.value){clearInterval(poll.value);poll.value=undefined}}
function connect(){if(session.enterpriseToken){connected.value=false;if(!poll.value)poll.value=window.setInterval(()=>{if(!document.hidden)load()},15000);return}source.value?.close();source.value=new EventSource('/tk-api/enterprise/stream');source.value.onopen=()=>{connected.value=true;stopPoll()};source.value.addEventListener('device-status',()=>load());source.value.onerror=()=>{connected.value=false;source.value?.close();if(!poll.value)poll.value=window.setInterval(()=>{if(!document.hidden)load()},15000);if(reconnect.value)clearTimeout(reconnect.value);reconnect.value=window.setTimeout(()=>{if(!document.hidden)connect()},30000)}}
function visibility(){if(document.hidden){source.value?.close();connected.value=false}else{load();connect()}}
onMounted(async()=>{await load();connect();document.addEventListener('visibilitychange',visibility)});onBeforeUnmount(()=>{source.value?.close();stopPoll();if(reconnect.value)clearTimeout(reconnect.value);document.removeEventListener('visibilitychange',visibility)})
</script>
<template><div class="page-stack"><section class="command-hero"><div><span class="eyebrow light">ENTERPRISE OVERVIEW</span><h2>{{roleTitle}}</h2><p>先看整体结论，再处理影响开播的设备、网络和采集异常。</p></div><div class="readiness-ring"><strong>{{onlineRate}}%</strong><span>设备在线率</span></div></section>
<div class="live-strip"><span :class="['live-dot',{off:!connected}]"></span>{{connected?'实时通道已连接':'实时通道重连中 · 已降级轮询'}}<small>更新于 {{updated}}</small></div>
<section class="metrics-grid"><MetricCard label="在线设备" :value="`${data.metrics.online||0}/${data.metrics.devices||0}`" tone="blue"/><MetricCard label="可以开播" :value="data.metrics.ready||0" tone="green"/><MetricCard label="系统阻断" :value="data.metrics.blocked||0" tone="red"/><MetricCard label="网络风险" :value="data.metrics.network_risk||0" tone="amber"/><MetricCard label="LIVE Studio运行" :value="data.metrics.studio_running||0" tone="violet"/><MetricCard label="未处理告警" :value="data.metrics.open_alerts||0" tone="red"/></section>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">FLEET STATUS</span><h3>需要关注的设备</h3></div><span class="quota">设备额度 {{data.metrics.devices||0}} / {{data.subscription.device_limit||'-'}}</span></header><div class="device-grid"><article v-for="d in data.devices" :key="d.device_id" class="device-tile" :class="d.online?d.readiness_state:'offline'"><header><b>{{d.display_name}}</b><StatusPill :value="d.online?'online':'offline'"/></header><p>{{d.store_name||'未设置门店'}} · {{d.owner_name||'未设置负责人'}}</p><div><StatusPill :value="d.readiness_state"/><StatusPill :value="d.studio_state"/></div><footer><span>{{d.target_region_id}}</span><span>V{{d.agent_version||d.app_version||'-'}}</span></footer></article><div v-if="!data.devices?.length" class="empty-state"><b>还没有接入设备</b><p>完成客户端安装和直播间绑定后，设备状态会显示在这里。</p></div></div></section></div></template>
