<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,ref} from 'vue';import {api} from '../api';import MetricCard from '../components/MetricCard.vue';import StatusPill from '../components/StatusPill.vue'
const data=ref<any>({metrics:{},devices:[],subscription:{}}),connected=ref(false),updated=ref(''),source=ref<EventSource|null>(null),poll=ref<number>(),reconnect=ref<number>()
const onlineRate=computed(()=>data.value.metrics.devices?Math.round(data.value.metrics.online/data.value.metrics.devices*100):0)
async function load(){data.value=await api('/tk-api/enterprise/overview');updated.value=new Date().toLocaleTimeString()}
function stopPoll(){if(poll.value){clearInterval(poll.value);poll.value=undefined}}
function connect(){source.value?.close();source.value=new EventSource('/tk-api/enterprise/stream');source.value.onopen=()=>{connected.value=true;stopPoll()};source.value.addEventListener('device-status',()=>load());source.value.onerror=()=>{connected.value=false;source.value?.close();if(!poll.value)poll.value=window.setInterval(()=>{if(!document.hidden)load()},15000);if(reconnect.value)clearTimeout(reconnect.value);reconnect.value=window.setTimeout(()=>{if(!document.hidden)connect()},30000)}}
function visibility(){if(document.hidden){source.value?.close();connected.value=false}else{load();connect()}}
onMounted(async()=>{await load();connect();document.addEventListener('visibilitychange',visibility)});onBeforeUnmount(()=>{source.value?.close();stopPoll();if(reconnect.value)clearTimeout(reconnect.value);document.removeEventListener('visibilitychange',visibility)})
</script>
<template><div class="page-stack"><section class="command-hero"><div><span class="eyebrow">LIVE READINESS COMMAND</span><h2>企业开播实时作战中心</h2><p>提前发现系统阻断、网络风险和软件异常，让每台电脑在开播前处于可控状态。</p></div><div class="readiness-ring"><strong>{{onlineRate}}%</strong><span>设备在线率</span></div></section>
<div class="live-strip"><span :class="['live-dot',{off:!connected}]"></span>{{connected?'实时通道已连接':'实时通道重连中 · 已降级轮询'}}<small>更新于 {{updated}}</small></div>
<section class="metrics-grid"><MetricCard label="在线设备" :value="`${data.metrics.online||0}/${data.metrics.devices||0}`" tone="blue"/><MetricCard label="可以开播" :value="data.metrics.ready||0" tone="green"/><MetricCard label="系统阻断" :value="data.metrics.blocked||0" tone="red"/><MetricCard label="网络风险" :value="data.metrics.network_risk||0" tone="amber"/><MetricCard label="LIVE Studio运行" :value="data.metrics.studio_running||0" tone="violet"/><MetricCard label="未处理告警" :value="data.metrics.open_alerts||0" tone="red"/></section>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">FLEET STATUS</span><h3>实时设备矩阵</h3></div><span class="quota">设备额度 {{data.metrics.devices||0}} / {{data.subscription.device_limit||'-'}}</span></header><div class="device-grid"><article v-for="d in data.devices" :key="d.device_id" class="device-tile" :class="d.online?d.readiness_state:'offline'"><header><b>{{d.display_name}}</b><StatusPill :value="d.online"/></header><p>{{d.store_name||'未设置门店'}} · {{d.owner_name||'未设置负责人'}}</p><div><StatusPill :value="d.readiness_state"/><StatusPill :value="d.studio_state"/></div><footer><span>{{d.target_region_id}}</span><span>V{{d.app_version||'-'}}</span></footer></article><div v-if="!data.devices?.length" class="empty-state">尚未绑定设备，请在“设备管理”生成绑定码。</div></div></section></div></template>
