<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{api}from'../api'
const rows=ref<any[]>([]),loading=ref(true),error=ref(''),show=ref(false),saving=ref(false)
const form=reactive({feature_code:'',feature_name:'',category:'enterprise',description:'',client_type:'all',default_enabled:false,status:'internal',minimum_client_version:'',config_schema:{}})
const rolloutFeature=ref(''),rollouts=ref<any[]>([]),rollout=reactive({rollout_type:'percentage',percentage:10,organization_ids:[],device_ids:[],minimum_version:'',starts_at:null,ends_at:null,status:'active'})
async function load(){loading.value=true;error.value='';try{rows.value=(await api('/api/v2/platform/features')).items}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function create(){saving.value=true;try{await api('/api/v2/platform/features',{method:'POST',body:JSON.stringify(form)});show.value=false;Object.assign(form,{feature_code:'',feature_name:'',category:'enterprise',description:'',client_type:'all',default_enabled:false,status:'internal',minimum_client_version:'',config_schema:{}});await load()}catch(e:any){error.value=e.message}finally{saving.value=false}}
async function toggle(row:any){await api(`/api/v2/platform/features/${row.id}`,{method:'PUT',body:JSON.stringify({...row,config_schema:row.config_schema,status:row.status==='enabled'?'disabled':'enabled'})});await load()}
async function loadRollouts(){if(!rolloutFeature.value){rollouts.value=[];return}rollouts.value=(await api(`/api/v2/platform/features/${rolloutFeature.value}/rollouts`)).items}
async function createRollout(){if(!rolloutFeature.value)return;try{await api(`/api/v2/platform/features/${rolloutFeature.value}/rollouts`,{method:'POST',body:JSON.stringify(rollout)});await loadRollouts()}catch(e:any){error.value=e.message}}
onMounted(load)
</script>
<template><div class="page-stack"><section class="panel"><header class="panel-head"><div><span class="eyebrow">FEATURE GOVERNANCE</span><h2>功能模块中心</h2><p>统一管理套餐、企业、设备和客户端版本可以使用的能力。</p></div><button class="primary" @click="show=!show">新建功能</button></header>
<form v-if="show" class="feature-form" @submit.prevent="create"><label>功能代码<input v-model="form.feature_code" placeholder="例如 live_dashboard" required></label><label>功能名称<input v-model="form.feature_name" placeholder="业务名称" required></label><label>分类<select v-model="form.category"><option>enterprise</option><option>device</option><option>live</option><option>analysis</option><option>client</option></select></label><label>使用端<select v-model="form.client_type"><option value="all">全部</option><option value="platform_admin">平台后台</option><option value="enterprise_admin">企业后台</option><option value="windows_client">Windows客户端</option><option value="api">API</option></select></label><label>最低版本<input v-model="form.minimum_client_version" placeholder="例如 2.2.0"></label><label>发布状态<select v-model="form.status"><option value="internal">内部</option><option value="beta">测试</option><option value="enabled">已启用</option><option value="disabled">已停用</option></select></label><div class="form-actions"><button type="button" @click="show=false">取消</button><button class="primary" :disabled="saving">{{saving?'正在创建…':'确认创建'}}</button></div></form>
<div v-if="loading" class="state-inline">正在获取功能模块……</div><div v-else-if="error" class="state-inline error"><b>暂时无法加载功能</b><span>{{error}}</span><button @click="load">立即重试</button></div><div v-else-if="!rows.length" class="empty-state">还没有功能模块。创建后可配置套餐和企业授权。</div><div v-else class="responsive-table"><table><thead><tr><th>功能</th><th>分类</th><th>使用端</th><th>状态</th><th>默认</th><th>最低版本</th><th>操作</th></tr></thead><tbody><tr v-for="x in rows" :key="x.id"><td><b>{{x.feature_name}}</b><small>{{x.feature_code}}</small></td><td>{{x.category}}</td><td>{{x.client_type}}</td><td><span :class="['feature-status',x.status]">{{x.status}}</span></td><td>{{x.default_enabled?'开启':'关闭'}}</td><td>{{x.minimum_client_version||'无限制'}}</td><td><button class="text-button" @click="toggle(x)">{{x.status==='enabled'?'停用':'启用'}}</button></td></tr></tbody></table></div></section><section class="panel"><header class="panel-head"><div><h3>灰度发布</h3><p>按比例逐步开放新功能，降低一次性发布风险。</p></div></header><div class="rollout-form"><label>目标功能<select v-model="rolloutFeature" @change="loadRollouts"><option value="">选择功能</option><option v-for="x in rows" :value="String(x.id)">{{x.feature_name}}</option></select></label><label>发布范围<select v-model="rollout.rollout_type"><option value="percentage">按比例</option><option value="all">全部</option><option value="internal">内部设备</option></select></label><label>灰度比例<input v-model.number="rollout.percentage" type="number" min="0" max="100"></label><label>最低版本<input v-model="rollout.minimum_version" placeholder="例如 2.2.0"></label><button :disabled="!rolloutFeature" @click="createRollout">创建灰度规则</button></div><div v-if="rolloutFeature&&!rollouts.length" class="empty-state compact">当前功能还没有灰度规则。</div><div class="rollout-list"><article v-for="x in rollouts" :key="x.id"><b>{{x.rollout_type==='percentage'?`${x.percentage}% 灰度`:x.rollout_type}}</b><span>最低版本 {{x.minimum_version||'无限制'}}</span><em>{{x.status}}</em></article></div></section></div></template>
