<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{session}from'../api';import{enterpriseApi}from'../services/enterprise';import StatusPill from'../components/StatusPill.vue'
const rows=ref<any[]>([]),audit=ref<any[]>([]),show=ref(false),showAudit=ref(false),loading=ref(true),saving=ref(false),error=ref(''),notice=ref('');const form=reactive({username:'',password:'',display_name:'',role:'viewer'});const roles=[{code:'owner',name:'企业主管',note:'企业资料、成员、设备和功能管理'},{code:'manager',name:'企业经理',note:'设备与绑定管理，不可管理成员'},{code:'operator',name:'企业运维',note:'实时设备、检测与换绑操作'},{code:'viewer',name:'只读人员',note:'只读查看工作台、设备和配置'}]
const currentId=computed(()=>session.bootstrap?.member?.id)
async function load(){loading.value=true;error.value='';try{rows.value=(await enterpriseApi.members()).items||[]}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function create(){saving.value=true;error.value='';try{await enterpriseApi.createMember(form);show.value=false;Object.assign(form,{username:'',password:'',display_name:'',role:'viewer'});await load();notice.value='成员已创建，可使用企业代码、账号和初始密码登录；建议首次登录后立即更换密码。'}catch(e:any){error.value=`创建失败：${e.message}`}finally{saving.value=false}}
async function update(row:any,active=row.active){if(row.id===currentId.value&&(!active||row.role!=='owner')){error.value='当前登录的企业主管不能停用或降级自己。';return}if(active!==row.active&&!window.confirm(`${active?'恢复':'停用'}成员 ${row.display_name||row.username}？`))return;try{await enterpriseApi.updateMember(row.id,{role:row.role,active});await load();notice.value=`已${active?'恢复':'停用'} ${row.display_name||row.username}，${active?'账号可以继续登录。':'该成员的现有会话已撤销。'}`}catch(e:any){error.value=e.message}}
async function openAudit(){try{audit.value=(await enterpriseApi.audit()).items.filter((x:any)=>x.target_type==='organization_member');showAudit.value=true}catch(e:any){error.value=e.message}}
onMounted(load)
</script>
<template><div class="page-stack"><section class="panel"><header class="panel-head"><div><span class="eyebrow">TEAM ACCESS</span><h2>组织管理</h2><p>成员角色、登录状态和敏感变更审计集中管理；当前会话受到自我停用保护。</p></div><div class="action-cluster"><button @click="openAudit">查看成员审计</button><button class="primary" @click="show=!show">新增成员</button></div></header><div class="role-guide"><article v-for="x in roles"><b>{{x.name}}</b><small>{{x.note}}</small></article></div><form v-if="show" class="member-form" @submit.prevent="create"><label>登录账号<input v-model="form.username" minlength="3" maxlength="80" required></label><label>姓名<input v-model="form.display_name" maxlength="80"></label><label>初始密码<input v-model="form.password" type="password" minlength="8" required></label><label>角色<select v-model="form.role"><option v-for="x in roles" :value="x.code">{{x.name}}</option></select></label><footer><button type="button" @click="show=false">取消</button><button class="primary" :disabled="saving">{{saving?'正在创建…':'创建成员'}}</button></footer></form><div v-if="notice" class="success-banner">{{notice}}</div><div v-if="error" class="form-error">{{error}}</div><div v-if="loading" class="skeleton-table"><i v-for="n in 5" class="skeleton"></i></div><div v-else-if="!rows.length" class="empty-state"><b>还没有企业成员</b><p>创建首位成员后，成员可从同一后台入口登录。</p></div><div v-else class="responsive-table"><table><thead><tr><th>成员</th><th>角色</th><th>状态</th><th>创建时间</th><th>会话保护</th><th>操作</th></tr></thead><tbody><tr v-for="x in rows" :key="x.id"><td data-label="成员"><b>{{x.display_name||x.username}}</b><small>{{x.username}}</small></td><td data-label="角色"><select v-model="x.role" :disabled="x.id===currentId" @change="update(x)"><option v-for="r in roles" :value="r.code">{{r.name}}</option></select></td><td data-label="状态"><StatusPill :value="x.active?'online':'disabled'"/></td><td data-label="创建时间">{{String(x.created_at).replace('T',' ').slice(0,19)}}</td><td data-label="会话保护"><span v-if="x.id===currentId" class="source-chip enabled">当前登录账号</span><span v-else>角色变更下次请求生效</span></td><td data-label="操作"><button v-if="x.id!==currentId" :class="x.active?'danger-text':'text-button'" @click="update(x,!x.active)">{{x.active?'停用':'恢复'}}</button><span v-else class="muted-text">不可停用自己</span></td></tr></tbody></table></div></section><div v-if="showAudit" class="drawer-mask" @click.self="showAudit=false"><aside class="detail-drawer"><header><div><span class="eyebrow">MEMBER AUDIT</span><h2>成员变更审计</h2></div><button class="drawer-close" @click="showAudit=false">×</button></header><div v-if="!audit.length" class="empty-state">暂无成员变更审计。</div><div v-else class="timeline"><article v-for="x in audit"><i></i><div><b>{{x.action}}</b><p>{{x.actor}} · 成员 #{{x.target_id}}</p></div><small>{{x.created_at?.replace('T',' ').slice(0,19)}}</small></article></div></aside></div></div></template>
