<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{api,loadBootstrap,session}from'../api';import{useRouter}from'vue-router'
const router=useRouter(),step=ref(1),saving=ref(false),error=ref('');const form=reactive({room_name:'',region:'',account_name:'',anchor_name:''});const labels=['企业信息','创建直播间','添加 TikTok 账号','添加主播','安装客户端','绑定电脑','完成'];const progress=computed(()=>Math.round((step.value-1)/6*100))
async function saveProgress(completed=false){await api('/api/v2/organization/onboarding',{method:'PUT',body:JSON.stringify({step:step.value,completed})})}
async function next(){saving.value=true;error.value='';try{if(step.value===2&&form.room_name)await api('/api/v2/organization/rooms',{method:'POST',body:JSON.stringify({name:form.room_name,region:form.region})});if(step.value===3&&form.account_name)await api('/api/v2/organization/accounts',{method:'POST',body:JSON.stringify({display_name:form.account_name})});if(step.value===4&&form.anchor_name)await api('/api/v2/organization/anchors',{method:'POST',body:JSON.stringify({display_name:form.anchor_name})});if(step.value<7){step.value++;await saveProgress()}else{await saveProgress(true);await loadBootstrap();router.replace({name:'enterprise-dashboard'})}}catch(e:any){error.value=e.message}finally{saving.value=false}}
async function later(){await saveProgress();router.replace({name:'enterprise-dashboard'})}
onMounted(()=>{step.value=session.bootstrap?.organization?.onboarding?.step||1})
</script>
<template><section class="onboarding-shell"><header><span>企业配置完成度</span><b>{{step-1}} / 7</b><i><em :style="{width:`${progress}%`}"></em></i></header><div class="onboarding-steps"><button v-for="(x,index) in labels" :class="{active:index+1===step,done:index+1<step}"><span>{{index+1<step?'✓':index+1}}</span>{{x}}</button></div><section class="panel onboarding-card"><span class="eyebrow">STEP {{step}} OF 7</span><template v-if="step===1"><h2>确认企业信息</h2><p>当前企业：{{session.bootstrap?.organization?.name}}。企业代码：{{session.bootstrap?.organization?.code}}</p></template><template v-else-if="step===2"><h2>创建第一个直播间</h2><p>直播间用于归属电脑、账号和后续直播数据。</p><input v-model="form.room_name" placeholder="例如：洛杉矶 1 号直播间"><input v-model="form.region" placeholder="目标地区，例如：美国西部"></template><template v-else-if="step===3"><h2>添加 TikTok 账号</h2><p>只保存企业内部识别名称，不读取密码和 Cookie。</p><input v-model="form.account_name" placeholder="例如：@mia_shop_us"></template><template v-else-if="step===4"><h2>添加主播</h2><p>填写企业内部使用的主播名称。</p><input v-model="form.anchor_name" placeholder="例如：Mia"></template><template v-else-if="step===5"><h2>安装 Windows 客户端</h2><p>在开播电脑安装 VD Nexus，客户端会自动识别本机设备，无需输入设备编号。</p></template><template v-else-if="step===6"><h2>绑定开播电脑</h2><p>在客户端输入企业代码并登录，然后选择直播间、TikTok 账号和主播。</p></template><template v-else><h2>基础配置已完成</h2><p>进入工作台后，可以继续接入设备、查看状态和处理异常。</p></template><div v-if="error" class="form-error">{{error}}</div><footer><button v-if="step<7" @click="later">稍后继续</button><button class="primary" :disabled="saving" @click="next">{{step===7?'进入工作台':saving?'正在保存…':'继续'}}</button></footer></section></section></template>
