<script setup lang="ts">
import{computed,onMounted,ref}from'vue';import{platformApi}from'../services/platform'
const organizations=ref<any[]>([]),organizationId=ref(''),query=ref(''),data=ref<any>(null),rows=ref<any[]>([]),baseline=ref('[]'),loading=ref(true),saving=ref(false),error=ref(''),notice=ref('')
const filteredOrganizations=computed(()=>organizations.value.filter(x=>!query.value||`${x.name} ${x.tenant_code}`.toLowerCase().includes(query.value.toLowerCase()))),dirty=computed(()=>JSON.stringify(rows.value)!==baseline.value)
const toLocal=(value:any)=>value?String(value).slice(0,16):''
function parseConfig(row:any){try{const value=JSON.parse(row.configText||'{}');if(!value||Array.isArray(value)||typeof value!=='object')throw new Error();return value}catch{throw new Error(`${row.name} 的配置不是有效 JSON 对象`)}}
async function boot(){try{organizations.value=(await platformApi.organizations()).tenants||[];if(organizations.value.length){organizationId.value=String(organizations.value[0].id);await load()}}catch(e:any){error.value=e.message;loading.value=false}}
async function load(){if(!organizationId.value)return;loading.value=true;error.value='';notice.value='';try{data.value=await platformApi.organizationFeatures(organizationId.value);rows.value=Object.entries(data.value.features).map(([code,value])=>{const x:any=value,o=x.override;return{code,name:x.name,category:x.category,mode:o?(o.enabled?'enabled':'disabled'):'inherit',source:o?.source||'manual',starts_at:toLocal(o?.starts_at),expires_at:toLocal(o?.expires_at),configText:JSON.stringify(o?.config||{},null,2),effective:x.enabled,effectiveSource:x.source,reason:x.reason}});baseline.value=JSON.stringify(rows.value)}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function save(){if(!dirty.value)return;const changed=rows.value.filter((x,i)=>JSON.stringify(x)!==JSON.stringify(JSON.parse(baseline.value)[i]));let items:any[];try{items=changed.filter(x=>x.mode!=='inherit').map(x=>({feature_code:x.code,enabled:x.mode==='enabled',source:x.source,starts_at:x.starts_at||null,expires_at:x.expires_at||null,config:parseConfig(x)}))}catch(e:any){error.value=e.message;return}if(!window.confirm(`将修改 ${data.value.organization.name} 的 ${changed.length} 项功能覆盖，确认继续吗？`))return;saving.value=true;try{for(const x of changed.filter(x=>x.mode==='inherit')){if(JSON.parse(baseline.value).find((b:any)=>b.code===x.code)?.mode!=='inherit')await platformApi.clearOrganizationFeature(organizationId.value,x.code)}if(items.length)await platformApi.saveOrganizationFeatures(organizationId.value,items);await load();notice.value=`授权已更新。${data.value.organization.name} 的客户端配置版本已刷新。`}catch(e:any){error.value=`授权保存失败：${e.message}。未提交的内容仍保留。`}finally{saving.value=false}}
async function clearRow(row:any){if(row.mode==='inherit'||!window.confirm(`清除“${row.name}”的企业覆盖并恢复套餐继承？`))return;try{await platformApi.clearOrganizationFeature(organizationId.value,row.code);await load();notice.value=`已清除 ${row.name} 的企业覆盖，当前按套餐继承。`}catch(e:any){error.value=e.message}}
onMounted(boot)
</script>
<template><div class="page-stack"><section class="panel"><header class="panel-head"><div><span class="eyebrow">ORGANIZATION ENTITLEMENTS</span><h2>企业功能授权</h2><p>对套餐继承值进行企业级覆盖、限时试用或恢复，最终生效来源清晰可追踪。</p></div><div class="action-cluster"><span v-if="dirty" class="dirty-badge">有未保存变化</span><button :disabled="!dirty" @click="load">恢复</button><button class="primary" :disabled="!dirty||saving" @click="save">{{saving?'正在保存…':'保存授权'}}</button></div></header><div class="filter-grid compact-grid"><input v-model="query" placeholder="搜索企业名称或代码"><select v-model="organizationId" @change="load"><option value="" disabled>选择企业</option><option v-for="x in filteredOrganizations" :value="String(x.id)">{{x.name}} · {{x.tenant_code}}</option></select><div v-if="data" class="context-card"><span>套餐</span><b>{{data.organization.plan_code}}</b></div><div v-if="data" class="context-card"><span>配置版本</span><b>{{data.config_version}}</b></div></div><div v-if="notice" class="success-banner">{{notice}}</div><div v-if="error" class="state-inline error"><b>企业授权未加载</b><span>{{error}}</span><button @click="load">立即重试</button></div><div v-else-if="loading" class="skeleton-table"><i v-for="n in 6" class="skeleton"></i></div><div v-else-if="!rows.length" class="empty-state"><b>没有可展示的功能</b><p>请先选择企业或在功能中心建立功能。</p></div><div v-else class="entitlement-editor"><article v-for="x in rows" :key="x.code"><header><div><b>{{x.name}}</b><small>{{x.code}} · {{x.category}}</small></div><span :class="['source-chip',x.effective?'enabled':'disabled']">最终{{x.effective?'启用':'关闭'}} · {{x.effectiveSource}}</span></header><div class="entitlement-fields"><label>企业策略<select v-model="x.mode"><option value="inherit">继承套餐</option><option value="enabled">强制启用</option><option value="disabled">强制关闭</option></select></label><label>来源<select v-model="x.source" :disabled="x.mode==='inherit'"><option value="manual">人工授权</option><option value="trial">限时试用</option><option value="promotion">活动授权</option><option value="system">系统策略</option></select></label><label>开始时间<input v-model="x.starts_at" :disabled="x.mode==='inherit'" type="datetime-local"></label><label>过期时间<input v-model="x.expires_at" :disabled="x.mode==='inherit'" type="datetime-local"></label><label class="wide">配置 JSON<textarea v-model="x.configText" :disabled="x.mode==='inherit'" rows="2" spellcheck="false"></textarea></label></div><footer><span v-if="x.reason">提示：{{x.reason}}</span><button class="text-button" :disabled="x.mode==='inherit'" @click="clearRow(x)">清除覆盖</button></footer></article></div></section></div></template>
