<script setup lang="ts">
import{computed,onMounted,ref}from'vue';import{platformApi}from'../services/platform'
const plans=[{code:'trial',name:'试用版'},{code:'basic',name:'基础版'},{code:'pro',name:'专业版'},{code:'custom',name:'定制版'}]
const plan=ref('trial'),features=ref<any[]>([]),organizations=ref<any[]>([]),baseline=ref('[]'),loading=ref(true),saving=ref(false),error=ref(''),notice=ref('')
const dirty=computed(()=>JSON.stringify(features.value)!==baseline.value),affected=computed(()=>organizations.value.filter(x=>x.plan_code===plan.value).length)
const format=(value:any)=>JSON.stringify(value||{},null,2)
function parse(value:string,label:string){try{const parsed=JSON.parse(value||'{}');if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw new Error();return parsed}catch{throw new Error(`${label} 必须是 JSON 对象`)}}
async function load(){loading.value=true;error.value='';notice.value='';try{const[definitions,assigned,orgs]=await Promise.all([platformApi.definitions(),platformApi.planFeatures(plan.value),platformApi.organizations()]);organizations.value=orgs.tenants||[];const map=new Map<string,any>(assigned.items.map((x:any)=>[x.feature_code,x]));features.value=definitions.items.map((x:any)=>{const row=map.get(x.feature_code);return{code:x.feature_code,name:x.feature_name,category:x.category,enabled:row?.enabled??x.default_enabled,limitsText:format(row?.limits),configText:format(row?.config),assigned:!!row}});baseline.value=JSON.stringify(features.value)}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function save(){if(!dirty.value)return;let items:any[];try{items=features.value.map(x=>({feature_code:x.code,enabled:x.enabled,limits:parse(x.limitsText,`${x.name} limits`),config:parse(x.configText,`${x.name} config`)}))}catch(e:any){error.value=e.message;return}if(!window.confirm(`将更新 ${plan.value} 套餐并影响 ${affected.value} 家企业，确认保存吗？`))return;saving.value=true;error.value='';try{await platformApi.savePlanFeatures(plan.value,items);notice.value=`已保存 ${plan.value} 套餐，${affected.value} 家企业将在下次刷新时获得新配置。`;await load();notice.value=`已保存 ${plan.value} 套餐，${affected.value} 家企业将在下次刷新时获得新配置。`}catch(e:any){error.value=`保存失败：${e.message}。当前页面改动仍保留，请修正后重试。`}finally{saving.value=false}}
async function clearRow(row:any){if(!row.assigned||!window.confirm(`恢复“${row.name}”到功能默认值？`))return;try{await platformApi.clearPlanFeature(plan.value,row.code);notice.value=`已清除 ${row.name} 的套餐覆盖，最终值将回退到功能默认配置。`;await load()}catch(e:any){error.value=e.message}}
onMounted(load)
</script>
<template><div class="page-stack"><section class="panel"><header class="panel-head"><div><span class="eyebrow">PLAN ENTITLEMENTS</span><h2>套餐功能管理</h2><p>集中配置套餐能力、限制与客户端参数，保存前可完整核对影响范围。</p></div><div class="action-cluster"><span v-if="dirty" class="dirty-badge">有未保存变化</span><button :disabled="!dirty||saving" @click="load">恢复</button><button class="primary" :disabled="!dirty||saving" @click="save">{{saving?'正在保存…':'保存配置'}}</button></div></header><div class="toolbar"><select v-model="plan" @change="load"><option v-for="x in plans" :value="x.code">{{x.name}} · {{x.code}}</option></select><span class="quota">影响企业 {{affected}} 家</span><span class="quota">功能 {{features.length}} 项</span></div><div v-if="notice" class="success-banner">{{notice}}</div><div v-if="error" class="state-inline error"><b>套餐配置未完成</b><span>{{error}}</span><button @click="load">重新加载</button></div><div v-else-if="loading" class="skeleton-table"><i v-for="n in 6" class="skeleton"></i></div><div v-else-if="!features.length" class="empty-state"><b>没有可配置的功能</b><p>请先在功能中心建立功能定义。</p></div><div v-else class="responsive-table"><table><thead><tr><th>功能</th><th>套餐开关</th><th>Limits (JSON)</th><th>Config (JSON)</th><th>来源</th><th>操作</th></tr></thead><tbody><tr v-for="x in features" :key="x.code"><td data-label="功能"><b>{{x.name}}</b><small>{{x.code}} · {{x.category}}</small></td><td data-label="套餐开关"><label class="switch"><input v-model="x.enabled" type="checkbox"><i></i><span>{{x.enabled?'包含':'不包含'}}</span></label></td><td data-label="Limits"><textarea v-model="x.limitsText" rows="3" spellcheck="false"></textarea></td><td data-label="Config"><textarea v-model="x.configText" rows="3" spellcheck="false"></textarea></td><td data-label="来源"><span :class="['source-chip',x.assigned?'manual':'default']">{{x.assigned?'套餐覆盖':'功能默认'}}</span></td><td data-label="操作"><button class="text-button" :disabled="!x.assigned" @click="clearRow(x)">恢复默认</button></td></tr></tbody></table></div></section></div></template>
