<script setup lang="ts">
import{onMounted,ref}from'vue';import{enterpriseApi}from'../services/enterprise';import StatusPill from'../components/StatusPill.vue'
const rows=ref<any[]>([]),q=ref(''),detail=ref<any>(null),loading=ref(true),error=ref('')
async function load(){loading.value=true;error.value='';try{rows.value=(await enterpriseApi.reports(q.value)).items||[]}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function open(id:string){try{detail.value=(await enterpriseApi.report(id)).report}catch(e:any){error.value=e.message}}
function items(prefix:string){return detail.value?.items.filter((x:any)=>prefix==='system'?x.check_id.startsWith('system.')||x.check_id.startsWith('environment.'):x.check_id.startsWith(prefix+'.'))||[]}
onMounted(load)
</script>
<template><div class="page-stack"><section class="panel"><header class="panel-head"><div><span class="eyebrow">DIAGNOSTIC REPORTS</span><h2>运营分析 · 三类环境报告</h2><p>网络环境、系统环境和电脑性能使用客户端上传的同一份可信数据，旧类别不参与新结论。</p></div></header><div class="toolbar"><input v-model="q" placeholder="搜索设备、地区或结论" @keyup.enter="load"><button @click="load">搜索</button></div><div v-if="error" class="state-inline error"><b>检测报告暂时不可用</b><span>{{error}}</span><button @click="load">重新加载</button></div><div v-else-if="loading" class="skeleton-table"><i v-for="n in 6" class="skeleton"></i></div><div v-else-if="!rows.length" class="empty-state"><b>暂无检测报告</b><p>客户端完成三类环境检测并上传后，报告会显示在这里。</p></div><div v-else class="report-cards"><article v-for="x in rows" @click="open(x.report_id)"><header><div><b>{{x.device_id}}</b><small>{{x.checked_at?.replace('T',' ').slice(0,19)}}</small></div><StatusPill :value="x.readiness_level==='READY'?'ready':x.readiness_level==='NOT_READY'?'blocked':'warning'"/></header><h3>{{x.conclusion}}</h3><ul><li><span>网络环境</span>{{x.network_summary}}</li><li><span>系统环境</span>{{x.environment_summary}}</li><li><span>电脑性能</span>{{x.hardware_summary}}</li></ul><footer>{{x.target_region_id}} · 点击查看详情</footer></article></div></section><div v-if="detail" class="modal-mask" @click.self="detail=null"><section class="report-modal"><button class="drawer-close" @click="detail=null">×</button><span class="eyebrow">FULL DIAGNOSTIC EVIDENCE</span><h2>{{detail.conclusion}}</h2><p>{{detail.device_id}} · {{detail.checked_at}}</p><div class="report-sections"><article v-for="group in [{id:'network',name:'网络环境',summary:detail.summaries.network},{id:'system',name:'系统环境',summary:detail.summaries.system},{id:'performance',name:'电脑性能',summary:detail.summaries.performance}]"><header><div><h3>{{group.name}}</h3><p>{{group.summary}}</p></div><b>{{items(group.id).length}}项</b></header><div class="check-list"><div v-for="x in items(group.id)"><StatusPill :value="x.status==='PASS'?'ready':x.status==='FAIL'?'blocked':'warning'"/><span><b>{{x.title}}</b><small>{{x.value||x.diagnosis||'已完成检测'}}</small></span></div></div></article></div></section></div></div></template>
