<script setup lang="ts">
import{computed,onMounted,ref}from'vue';import{platformApi}from'../services/platform'
const roles=[{code:'owner',name:'企业主管'},{code:'manager',name:'企业经理'},{code:'operator',name:'企业运维'},{code:'viewer',name:'只读人员'}],actions=['read','create','update','delete','manage']
const organizations=ref<any[]>([]),organizationId=ref(''),role=ref('owner'),rows=ref<any[]>([]),basePermissions=ref<string[]>([]),baseline=ref(''),loading=ref(true),saving=ref(false),error=ref(''),notice=ref('')
const dirty=computed(()=>JSON.stringify(rows.value)!==baseline.value)
async function boot(){try{organizations.value=(await platformApi.organizations()).tenants||[];if(organizations.value.length){organizationId.value=String(organizations.value[0].id);await load()}}catch(e:any){error.value=e.message;loading.value=false}}
async function load(){if(!organizationId.value)return;loading.value=true;error.value='';notice.value='';try{const value=await platformApi.roleFeatures(organizationId.value,role.value);rows.value=value.items;basePermissions.value=value.base_permissions||[];baseline.value=JSON.stringify(rows.value)}catch(e:any){error.value=e.message}finally{loading.value=false}}
function batch(action:string,value:boolean){rows.value.forEach(x=>x[action]=value)}
async function save(){if(!dirty.value||!window.confirm(`保存 ${roles.find(x=>x.code===role.value)?.name} 的功能动作权限？`))return;saving.value=true;try{await platformApi.saveRoleFeatures(organizationId.value,role.value,rows.value.map(x=>({feature_code:x.feature_code,can_read:x.read,can_create:x.create,can_update:x.update,can_delete:x.delete,can_manage:x.manage})));await load();notice.value='角色权限矩阵已保存，企业成员下一次请求立即按新权限执行。'}catch(e:any){error.value=`保存失败：${e.message}。权限尚未改变，请检查后重试。`}finally{saving.value=false}}
async function reset(){if(!window.confirm('恢复该角色全部功能动作的系统默认值？此操作会删除人工权限覆盖。'))return;try{await platformApi.resetRoleFeatures(organizationId.value,role.value);await load();notice.value='已恢复系统默认权限。'}catch(e:any){error.value=e.message}}
onMounted(boot)
</script>
<template><div class="page-stack"><section class="panel"><header class="panel-head"><div><span class="eyebrow">ROLE PERMISSION MATRIX</span><h2>角色权限矩阵</h2><p>统一管理角色在各功能中的读取、新建、修改、删除和管理动作。</p></div><div class="action-cluster"><span v-if="dirty" class="dirty-badge">有未保存变化</span><button @click="reset">恢复默认</button><button class="primary" :disabled="!dirty||saving" @click="save">{{saving?'保存中…':'保存权限'}}</button></div></header><div class="toolbar"><select v-model="organizationId" @change="load"><option value="" disabled>选择企业</option><option v-for="x in organizations" :value="String(x.id)">{{x.name}}</option></select><div class="segmented no-margin"><button v-for="x in roles" :class="{active:role===x.code}" @click="role=x.code;load()">{{x.name}}</button></div></div><div class="permission-hint"><b>基础权限</b><span v-if="basePermissions.length">{{basePermissions.join(' · ')}}</span><span v-else>当前角色没有基础权限，功能动作授权也不会绕过基础权限。</span></div><div v-if="notice" class="success-banner">{{notice}}</div><div v-if="error" class="state-inline error"><b>权限矩阵未加载</b><span>{{error}}</span><button @click="load">重试</button></div><div v-else-if="loading" class="skeleton-table"><i v-for="n in 6" class="skeleton"></i></div><div v-else-if="!rows.length" class="empty-state"><b>没有功能权限项</b><p>请先在功能中心创建功能定义。</p></div><template v-else><div class="matrix-batch"><span>批量设置：</span><template v-for="action in actions"><button @click="batch(action,true)">全开 {{action}}</button><button @click="batch(action,false)">全关 {{action}}</button></template></div><div class="responsive-table role-matrix"><table><thead><tr><th>功能</th><th v-for="action in actions">{{action}}</th><th>提示</th></tr></thead><tbody><tr v-for="x in rows" :class="{muted:!x.feature_enabled}"><td data-label="功能"><b>{{x.feature_name}}</b><small>{{x.feature_code}} · {{x.category}}</small></td><td v-for="action in actions" :data-label="action"><label class="matrix-check"><input v-model="x[action]" type="checkbox"><i>✓</i></label></td><td data-label="提示"><span v-if="!x.feature_enabled" class="conflict-note">功能当前关闭，动作权限暂不生效</span><span v-else-if="x.manage&&!basePermissions.length" class="conflict-note">受基础权限限制</span><span v-else class="source-chip enabled">可生效</span></td></tr></tbody></table></div></template></section></div></template>
