<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{api,session}from'../api'
const rows=ref<any[]>([]),show=ref(false),editing=ref<number|null>(null),canManage=session.permissions.includes('workorders.manage')
const form=reactive<any>({title:'',device_id:'',alert_id:null,priority:'medium',status:'open',owner:'',notes:'',resolution:''})
const metrics=computed(()=>({open:rows.value.filter(x=>x.status==='open').length,processing:rows.value.filter(x=>x.status==='processing').length,resolved:rows.value.filter(x=>['resolved','closed'].includes(x.status)).length}))
async function load(){rows.value=(await api('/tk-api/enterprise/work-orders')).work_orders}
function create(){editing.value=null;Object.assign(form,{title:'',device_id:'',alert_id:null,priority:'medium',status:'open',owner:'',notes:'',resolution:''});show.value=true}
function edit(x:any){editing.value=x.id;Object.assign(form,x);show.value=true}
async function save(){await api('/tk-api/enterprise/work-orders',{method:'POST',body:JSON.stringify({...form,id:editing.value})});show.value=false;load()}
function duration(x:any){if(!x.resolved_at)return '处理中';const ms=new Date(x.resolved_at).getTime()-new Date(x.created_at).getTime();return ms<3600000?`${Math.max(1,Math.round(ms/60000))}分钟`:`${(ms/3600000).toFixed(1)}小时`}
onMounted(load)
</script>
<template><div class="page-stack"><section class="work-metrics"><article><span>待处理</span><strong>{{metrics.open}}</strong></article><article><span>处理中</span><strong>{{metrics.processing}}</strong></article><article><span>已恢复</span><strong>{{metrics.resolved}}</strong></article></section><section class="panel"><header class="panel-head"><div><span class="eyebrow">INCIDENT WORKFLOW</span><h2>故障处理工单</h2><p>记录负责人、处理过程、解决结论和恢复时长。</p></div><button v-if="canManage" class="primary" @click="create">新建工单</button></header><form v-if="show" class="work-form" @submit.prevent="save"><label>故障标题<input v-model="form.title" required></label><label>设备编号<input v-model="form.device_id"></label><label>负责人<input v-model="form.owner"></label><label>优先级<select v-model="form.priority"><option value="medium">一般</option><option value="high">重要</option><option value="critical">紧急</option></select></label><label>状态<select v-model="form.status"><option value="open">待处理</option><option value="processing">处理中</option><option value="resolved">已解决</option><option value="closed">已关闭</option></select></label><label class="wide">处理记录<textarea v-model="form.notes" rows="3"></textarea></label><label class="wide">解决结论<textarea v-model="form.resolution" rows="3"></textarea></label><div class="work-form-actions"><button type="button" @click="show=false">取消</button><button class="primary">保存工单</button></div></form><div class="work-list"><article v-for="x in rows" @click="canManage&&edit(x)"><span class="priority" :class="x.priority">{{x.priority}}</span><div><b>{{x.title}}</b><p>{{x.device_id||'未关联设备'}} · 负责人 {{x.owner||'待指派'}} · 处理时长 {{duration(x)}}</p></div><span class="role-badge">{{x.status}}</span></article><div v-if="!rows.length" class="empty-state">暂无处理中工单</div></div></section></div></template>
